[package]
name = "lidarr-application"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
lidarr-config = { path = "../lidarr-config" }
lidarr-domain = { path = "../lidarr-domain" }
tracing = { workspace = true }
