[package]
name = "chorrosion-config"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
figment = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
